name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Run Build
      run: make
    - name: Run Test
      run: make test
